# Generated by Django 4.1.2 on 2022-10-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_job_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="Vacancy",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="experiance",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.IntegerField(default=0),
        ),
    ]
